### ISSUE TITLE
Meta: Write more passes

### ISSUE THREAD

**Issue by sgraf812** [dnlkrgr/hsreduce#1]
Find programs on which we perform less than ideal, think of passes that would improve the situation.

Programs on which we perform "less than ideal":

- [ ] ticket16979
- [ ] ticket8763
- [ ] ticket15753
- [ ] ticket18098
- [ ] ticket18140

Passes that could help:
- [x] more simplification of expressions by replacing it with subexpression (for example tuples)
- [x] more simplification of types by replacing them with parameter type
- [x] deleting unused parameters (wildcard patterns)
- [x] unqualifying imports 
- [x] unqualifying names
- [x] simplify deriving clauses
- [x] turn record constructors into prefix data constructors 
- [x] renaming / shortening of names
- [ ] un-polymorphize function, apply beta reduction on forall
- [x] simplifying data constructors, deleting unused type parameters
- [x] inlining data declarations with one data constructor
- [x] inlining type aliases
- [ ] evaluating / inlining template haskell 
- [ ] simplifying literals (for example Strings)
- [x] deleting type variables one by one from contexts
- [x] deleting type variables one by one from foralls
