### ISSUE TITLE
Meta: Collect statistics

### ISSUE THREAD

**Issue by sgraf812** [dnlkrgr/hsreduce#3]
Collect statistics about how well reduction works. Take inspiration in previous work, like 

- https://www.cs.utah.edu/~regehr/papers/pldi12-preprint.pdf
- https://pp.ipd.kit.edu/uploads/publikationen/stroessner18bachelorarbeit.pdf
- https://pp.ipd.kit.edu/uploads/publikationen/pkrueger19bachelorarbeit.pdf

TODO: Add interesting metrics to consider here. Edit description to do so

- [x] starting size, end size, reduction size
- [x] duration
- [x] number of tests per pass, number of successful tests per pass
- [x] number of removed bytes per pass
- [ ] how many other passes were enabled by a pass
  - problem: how to get the dependencies between passes
